# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: circleci/openjdk:8-jdk
      - image: circleci/android:api-29

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - run:
          name: Generate cache key
          command: ./gradle/checksum.sh /tmp/checksum.txt

      - restore_cache:
          keys:
            - gradle-{{ checksum "/tmp/checksum.txt" }}
            - gradle-
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/checksum.txt" }}

      # run tests!
      - run:
          name:  Run JUnit Tests
          command: ./gradlew lint test
      # save tests
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
